---
title: "Explorando os dados traumas"
author: "Felipe"
date: "25/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Carregando pacotes para manipulaC'C#o

```{r echo = FALSE}
#carregando pacotes de manipular dados
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(stringi))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readr))

#exporting as an html file
suppressPackageStartupMessages(library(knitr))
```

Carregando dados 

```{r}
dados_traumas <- read.csv("traumas.csv", na.strings = c("","NA"), sep = ";")
names(dados_traumas)
View(dados_traumas)
```

Filtrando dados do Peru e que contenha somente os perC-odos PIP,HM,PIT:

```{r}
data.tr.peru <- dados_traumas %>% filter(pais%in%c("Peru"))%>% slice(-1) #a funC'C#o slice C) usada para remover a primeira linha que contC)m um dado do Arcaico
                                           
View(data.tr.peru)
names(data.tr.peru)

```

DescriC'C#o dos dados:

```{r}
#install.packages("pastecs")
suppressPackageStartupMessages(library(pastecs))

data_descr <- data.tr.peru %>% select(n_id,n_id_traumas,sem_traumas,n_id_antimortem,n_id_perimortem)

descr <- stat.desc(data_descr)
round(descr,2)

```

```{r}
library(ggplot2)
data.tr.peru %>% filter(!is.na(n_id))%>%
                group_by(cronologia) %>% ggplot+geom_boxplot(aes(x=cronologia,y=n_id))

#falta alterar títulos e aparência 
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_traumas))%>%
                group_by(cronologia) %>% ggplot+geom_boxplot(aes(x=cronologia,y=n_id_traumas))
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_antimortem))%>%
                group_by(cronologia) %>% ggplot+geom_boxplot(aes(x=cronologia,y=n_id_antimortem))
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_perimortem))%>%
                group_by(cronologia) %>% ggplot+geom_boxplot(aes(x=cronologia,y=n_id_perimortem))
```


```{r}
data.tr.peru %>% filter(!is.na(n_id))%>%
                group_by(sexo) %>%  ggplot+geom_boxplot(aes(x=sexo,y=n_id))
```


```{r}
data.tr.peru %>% filter(!is.na(n_id_traumas))%>%
                group_by(sexo) %>%  ggplot+geom_boxplot(aes(x=sexo,y=n_id_traumas))
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_antimortem))%>%
                group_by(sexo) %>%  ggplot+geom_boxplot(aes(x=sexo,y=n_id_antimortem))
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_perimortem))%>%
                group_by(sexo) %>%  ggplot+geom_boxplot(aes(x=sexo,y=n_id_perimortem))
```


```{r}
names(data.tr.peru)
```

```{r}
data.tr.peru %>% filter(!is.na(n_id))%>% ggplot+geom_boxplot(aes(x=regiao,y=n_id))
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_traumas))%>% ggplot+geom_boxplot(aes(x=regiao,y=n_id_traumas))
# os resultados mostram que o vale de majes concentra mais casos de traumas, no entanto, só pussui 4 observações, isso é desproporcional em relação ao restante
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_antimortem))%>% ggplot+geom_boxplot(aes(x=regiao,y=n_id_antimortem))
```

```{r}
data.tr.peru %>% filter(!is.na(n_id_perimortem))%>% ggplot+geom_boxplot(aes(x=regiao,y=n_id_perimortem))
```

Testando proporção entre amostras e comparando médias usando Chiquadrado e Kruskal-Wallis respectivamente

```{r}

#carregando dados em tabela de contigencia para aplicar o chiquadrado

#por região
regiao <- read.csv("regiao_contigent.csv", sep = ";",row.names = 1) %>% slice(-3)  #usando a função slice para retirar as linhas 3 correspondente a região do vale de lurin que não possui dados pareados 
View(regiao)
#por região e sexo:
regiao_sexo <- read.csv("regiao_sexo_contigent.csv", sep = ";") %>% slice(-7,-8) #usando a função slice para retirar as linhas 7 e 8 correspondente a região do vale de lurin que não possui dados pareados por sexo
View(regiao_sexo)

#por periodo
periodo <- read.csv("periodo_contigent.csv", sep = ";")
View(periodo)

#por periodo e sexo:
periodo_sexo <-read.csv("periodo_sexo_contigent.csv", sep = ";",row.names = 1) %>% select(n_id,n_id_traumas,sem_traumas) %>% slice(-6)
names(periodo_sexo)
View(periodo_sexo)
```

Chiquadrado
```{r}

```

